# Generated by Django 3.0.7 on 2020-09-09 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='Address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
